import { UserRole, NavItem } from '../types';

export const getNavigationForRole = (role: UserRole): NavItem[] => {
  const navigationMap: Record<UserRole, NavItem[]> = {
    proprietor: [
      { title: 'Executive Summary', href: '/dashboard', icon: 'LayoutDashboard' },
      { title: 'Financial Hub', href: '/financial-hub', icon: 'DollarSign' },
      { title: 'HR Oversight', href: '/hr-oversight', icon: 'Users' },
      { title: 'Academic Analytics', href: '/academic-analytics', icon: 'TrendingUp' },
      { title: 'Class Management', href: '/class-management', icon: 'GraduationCap' },
      { title: 'Subject Management', href: '/subject-management', icon: 'BookOpen' },
      { title: 'Students Database', href: '/students-database', icon: 'Users' },
      { title: 'Staff Database', href: '/staff-database', icon: 'Briefcase' },
      { title: 'Transport Manifesto', href: '/transport-manifesto', icon: 'Bus' },
      { title: 'System Controls', href: '/system-controls', icon: 'Settings' },
      { title: 'Communication', href: '/communication', icon: 'MessageSquare' },
      { title: 'Audit Trail', href: '/audit-trail', icon: 'Activity' },
      { title: 'Account Settings', href: '/account-settings', icon: 'User' },
    ],
    principal: [
      { title: 'Academic Command Center', href: '/dashboard', icon: 'LayoutDashboard' },
      { title: 'Admission & CBT Portal', href: '/admission-portal', icon: 'GraduationCap' },
      { title: 'Curriculum & Lesson Notes', href: '/curriculum-management', icon: 'BookCheck' },
      { title: 'Examination & Results', href: '/examination-management', icon: 'Award' },
      { title: 'Attendance & Discipline', href: '/attendance-discipline', icon: 'CheckSquare' },
      { title: 'Timetable & Resources', href: '/timetable-resources', icon: 'Calendar' },
      { title: 'Class Management', href: '/class-management', icon: 'GraduationCap' },
      { title: 'Subject Management', href: '/subject-management', icon: 'BookOpen' },
      { title: 'Student Management', href: '/student-management', icon: 'Users' },
      { title: 'Staff Database', href: '/staff-database', icon: 'Briefcase' },
      { title: 'Transport Manifesto', href: '/transport-manifesto', icon: 'Bus' },
      { title: 'Communication Hub', href: '/communication-hub', icon: 'MessageSquare' },
      { title: 'System Control', href: '/system-controls', icon: 'Settings' },
    ],
    hr: [
      { title: 'HR Command Center', href: '/dashboard', icon: 'LayoutDashboard' },
      { title: 'Staff Directory', href: '/staff-directory', icon: 'Users' },
      { title: 'Attendance Tracking', href: '/attendance-tracking', icon: 'Clock' },
      { title: 'Class Management', href: '/class-management', icon: 'GraduationCap' },
      { title: 'Leave Management', href: '/leave-management', icon: 'Calendar' },
      { title: 'Recruitment', href: '/recruitment', icon: 'Briefcase' },
      { title: 'Performance', href: '/performance', icon: 'Award' },
      { title: 'Payroll Config', href: '/payroll-config', icon: 'DollarSign' },
    ],
    bursar: [
      { title: 'Dashboard', href: '/dashboard', icon: 'LayoutDashboard' },
      { title: 'Fee Management', href: '/fees', icon: 'Receipt' },
      { title: 'Payments', href: '/payments', icon: 'CreditCard' },
      { title: 'Invoice Generator', href: '/invoices', icon: 'FileText' },
      { title: 'Financial Ledger', href: '/ledger', icon: 'BookOpen' },
      { title: 'Reports', href: '/reports', icon: 'BarChart' },
      { title: 'Expenses', href: '/expenses', icon: 'TrendingDown' },
    ],
    teacher: [
      { title: 'Dashboard', href: '/dashboard', icon: 'LayoutDashboard' },
      { title: 'Daily Briefing', href: '/daily-briefing', icon: 'Calendar' },
      { title: 'Lesson Notes', href: '/lesson-notes', icon: 'BookOpen' },
      { title: 'Class Management', href: '/class-management', icon: 'GraduationCap' },
      { title: 'Subject Grading', href: '/gradebook', icon: 'ClipboardList' },
      { title: 'Assessments & CBT', href: '/assessments', icon: 'FileQuestion' },
      { title: 'Communication', href: '/communication', icon: 'MessageSquare' },
    ],
    student: [
      { title: 'Dashboard', href: '/dashboard', icon: 'LayoutDashboard' },
      { title: 'Learning Hub', href: '/learning-hub', icon: 'BookOpen' },
      { title: 'My Exams', href: '/exams', icon: 'FileQuestion' },
      { title: 'Results', href: '/results', icon: 'Award' },
      { title: 'Assignments', href: '/assignments', icon: 'ClipboardList' },
      { title: 'Timetable', href: '/timetable', icon: 'Calendar' },
      { title: 'Attendance', href: '/attendance', icon: 'CheckCircle' },
    ],
    parent: [
      { title: 'Family Hub', href: '/dashboard', icon: 'Home' },
      { title: 'School Calendar', href: '/school-calendar', icon: 'Calendar' },
      { title: 'Academic Monitor', href: '/academic-monitor', icon: 'Award' },
      { title: 'Fees & Payments', href: '/fee-management', icon: 'CreditCard' },
      { title: 'Assessment & Results', href: '/assessment-results', icon: 'FileText' },
      { title: 'Attendance & Schedule', href: '/attendance-tracking', icon: 'Calendar' },
      { title: 'Communication', href: '/parent-communication', icon: 'MessageSquare' },
    ],
  };

  return navigationMap[role] || [];
};